{pkgs,inputs, ...}: {
  environment.systemPackages = with pkgs; [
    alejandra
    cachix
    wget
    curl
    git
    htop
    nix-info
    wireguard-tools
    tree
    file
    binutils
    lsof
    dnsutils
    netcat
    usbutils
    pciutils
    #Documentation
    linux-manual
    man-pages
    man-pages-posix
    nix-doc
    nix-tree
    vscode
    nix-eval-jobs
    iptables
    openconnect
    globalprotect-openconnect
    wireshark
    inputs.mcp-nixos.packages."${pkgs.system}".default
  ];
}
